### ISSUE TITLE
HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)

### ISSUE THREAD

**Issue by neve360** [Blu-Tiger/StreamingCommunity-yt-dlp-plugin#1]
ottengo quest errore: 
comando: yt-dlp https://streamingcommunity.foo/watch/7540?e=50636
[StreamingCommunity] Extracting URL: https://streamingcommunity.foo/watch/7540?e=50636
[StreamingCommunity] 7540: Downloading webpage
[StreamingCommunity] 7540: Downloading webpage
[StreamingCommunity] 7540: Downloading webpage
[StreamingCommunity] 7540: Downloading m3u8 information
ERROR: [StreamingCommunity] 7540: Failed to download m3u8 information: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)

**Comment by Blu-Tiger** [comment]
Ci darò un occhiata

**Comment by Blu-Tiger** [comment]
Dovrei aver sistemato, prova a reinstallare il plugin e controlla che scarichi i video in modo corretto.

**Comment by neve360** [comment]
Ora funziona grazie
