### ISSUE TITLE
Failed to download m3u8 information: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by dennisloi** [Blu-Tiger/StreamingCommunity-yt-dlp-plugin#2]
I was getting the error in the title, I fixed it by adding the token to the url:
From this:
`dl_url = playlist_url + '?' + '&expires=' + playlist_info.get('expires')`
To this:
`dl_url = playlist_url + '&token=' + playlist_info.get('token') + '&expires=' + playlist_info.get('expires') + '&h=1'`

I tried adding the token list from tokens_url (which was a list of two identical tokens), but it didn't work.

**Comment by SRK7Kyros** [comment]
could you please show more of your code? it's difficult to understand what exactly `playlist_url` and `playlist_info` are.
I'm getting the same error, I'm trying to troubleshoot this myself.

**Comment by Blu-Tiger** [comment]
I'm working on it, something seems to have been changed in the site.
The playlist_info and playlist_url are dictionaries containing respectively the playlist m3u url and the token & expiration data, that are directly extracted from the page js embedded in the html returned by the iframe url, you can check by printing the iframe returned html.

Previously playlist_info contained multiple tokens for every video resolution in the playlist, then it for some reason became unused, now it seem to be only one token but the url also needs a resolution parameter.

**Comment by SRK7Kyros** [comment]
Alright, got it.  until a newer release, ill try to workaround as the op did in my own code. Thank you very much :)

**Comment by SRK7Kyros** [comment]
I was able to fix the code, ill make a pull request with the changes that allowed my script to finally work again

**Comment by SRK7Kyros** [comment]
the error is back for me, even with the newer code.

**Comment by Blu-Tiger** [comment]
I will look in to it again, it seems to work some times and some times not

**Comment by SRK7Kyros** [comment]
already trying to do that here, will update you here in case i find anything.

**Comment by SRK7Kyros** [comment]
found the problem. in its fix op added `&h=1` to the url, which i also included in my previous pr and that is causing the issue. removing it consistently works. filing a pr asap.

**Comment by MiticoBerna** [comment]
Hi, thank you all for the great work.

It seems the 403 is intermittent, I restored locally the `+ '&h=1'` and now works again.
Maybe the server expect a random number sometimes with param `h`? (`h=2` works too for example).

**Comment by Blu-Tiger** [comment]
The h parameter is set when the Playlist has hd streams in it, it should be automatically set of the steamingcommunity page has it set
